### ISSUE TITLE
Update next redux wrapper

### ISSUE THREAD

**Issue by mmiszy** [typeofweb/devfaq-www#8]

**Comment by mczeplowski** [comment]
I can do it.

**Comment by mmiszy** [comment]
We also need to decide on the strategy – we could migrate to complete static generation, but do we want to? Do we prefer to keep on using SSR?

**Comment by mczeplowski** [comment]
I think current way of rendering is good for this project.

**Comment by mczeplowski** [comment]
There is a problem with the newest version of next-redux-wrapper. After update and required changes application has a problem with routing. It is related to HYDRATE action added in 6 version of lib. Here you have simple use example of newest lib. https://github.com/vercel/next.js/blob/canary/examples/with-redux-wrapper/store/store.js

**Comment by mmiszy** [comment]
I did some research, and I guess you're right, there's no need to migrate away from `getInitialProps`

**Comment by mczeplowski** [comment]
If you wanna check how it works you can run app on my fork's branch `issue-8-migrate-from-getinitialprops`.
Here you can find required changes: https://github.com/typeofweb/devfaq-www/compare/develop...mczeplowski:issue-8-migrate-from-getinitialprops

**Comment by mczeplowski** [comment]
So 5th version of next redux wrapper is working with app with no changes. The newest version (6th) require some changes, but after them our app has breaking routing, so it will be a bigger task. You can check this running my branch.

**Comment by mmiszy** [comment]
Sounds good! Create a PR and I'll refactor routing later. I don't remember why I even did it this way.

**Comment by mmiszy** [comment]
Fixed in https://github.com/typeofweb/devfaq-www/pull/85
